### ISSUE TITLE
프론트엔드 개발 환경을 구축한다.

### ISSUE THREAD

**Issue by devFancy** [woorifisa-projects/2023-SUT#11]
## 기능 설명

프론트엔드 개발 환경을 구축한다.

해당 부분은 `master` 브랜치에서 작업합니다.

## 환경 설정(세부 내용)

- [x] TypeScript ,Vue.js
- [ ] Taliwind CSS
- [x] ESLint
- [x] Prettier
- [x] Pinia

## 소요 시간

- 결과:

**Comment by han0224** [comment]
tailwind css는 이후 css 작업할시 설치할 예정입니다
